//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tawbah.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tawbah.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adadalmawaqi {
            get {
                object obj = ResourceManager.GetObject("adadalmawaqi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alisdar {
            get {
                object obj = ResourceManager.GetObject("alisdar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chokr {
            get {
                object obj = ResourceManager.GetObject("chokr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\fbidis\ansi\ansicpg1256\deff0\nouicompat\deflang1025{\fonttbl{\f0\fnil\fcharset178 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red255\green110\blue50;\red0\green145\blue65;\red0\green176\blue80;\red192\green80\blue77;\red0\green151\blue68;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\rtlpar\ri57\li57\sa200\sl240\slmult1\qc\cf1\ul\f0\rtlch\fs36\&apos;d4\&apos;df\&apos;d1\ulnone\fs22\par
        ///\cf2\fs32\&apos;c3\&apos;e6\&apos;f8\&apos;e1\&apos;c7\&apos;a1\f1\ltrch\lang1036  \f0\rtlch\lang1025\&apos;c3\&apos;cd\&apos;e3\&apos;cf \b\&apos;c7\&apos;e1\&apos;e1\&apos;e5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chokr1 {
            get {
                return ResourceManager.GetString("chokr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap frame {
            get {
                object obj = ResourceManager.GetObject("frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hajb {
            get {
                object obj = ResourceManager.GetObject("hajb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap halmoqtarah {
            get {
                object obj = ResourceManager.GetObject("halmoqtarah", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hawla {
            get {
                object obj = ResourceManager.GetObject("hawla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iblagh {
            get {
                object obj = ResourceManager.GetObject("iblagh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isbir {
            get {
                object obj = ResourceManager.GetObject("isbir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isdarjadid {
            get {
                object obj = ResourceManager.GetObject("isdarjadid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itar21 {
            get {
                object obj = ResourceManager.GetObject("itar21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\fbidis\ansi\ansicpg1256\deff0\nouicompat\deflang1025{\fonttbl{\f0\fnil\fcharset178 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red255\green128\blue0;\red192\green80\blue77;\red0\green176\blue80;\red240\green120\blue0;\red128\green64\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\rtlpar\sa200\sl276\slmult1\qc\cf1\ul\f0\rtlch\fs36\&apos;c7\&apos;e1\&apos;ca\&apos;f8\&apos;d1\&apos;ce\&apos;ed\&apos;d5\par
        ///\cf2\ulnone\fs32\&apos;c7\&apos;e1\&apos;c8\&apos;d1\&apos;e4\&apos;c7\&apos;e3\&apos;cc\cf0  \cf3\ul\&apos;e3\&apos;cc\&apos;f8\&apos;c7\&apos;e4\&apos;ed\&apos;f8\cf0\ulnone\fs36\pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License1 {
            get {
                return ResourceManager.GetString("License1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightchokr {
            get {
                object obj = ResourceManager.GetObject("lightchokr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lighthajb {
            get {
                object obj = ResourceManager.GetObject("lighthajb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lighthawla {
            get {
                object obj = ResourceManager.GetObject("lighthawla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightiblagh {
            get {
                object obj = ResourceManager.GetObject("lightiblagh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightmawqi {
            get {
                object obj = ResourceManager.GetObject("lightmawqi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightsoalwajawab {
            get {
                object obj = ResourceManager.GetObject("lightsoalwajawab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lighttahaqoqnajah {
            get {
                object obj = ResourceManager.GetObject("lighttahaqoqnajah", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lighttahdith {
            get {
                object obj = ResourceManager.GetObject("lighttahdith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mawqi {
            get {
                object obj = ResourceManager.GetObject("mawqi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\fbidis\ansi\ansicpg1256\deff0\nouicompat\deflang1025{\fonttbl{\f0\fnil\fcharset178 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red255\green110\blue50;\red192\green0\blue0;\red0\green176\blue80;\red192\green80\blue77;\red38\green38\blue38;\red0\green0\blue255;\red60\green22\blue9;\red51\green51\blue51;\red226\green76\blue2;\red255\green255\blue255;\red83\green129\blue53;\red197\green89\blue17;\red0\green128\blue0;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\rtlpar\ri57\li57\sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nassasilawaajwiba {
            get {
                return ResourceManager.GetString("nassasilawaajwiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\fbidis\ansi\ansicpg1256\deff0\nouicompat\deflang1025{\fonttbl{\f0\fnil\fcharset178 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green176\blue80;\red192\green80\blue77;\red0\green0\blue255;}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\rtlpar\ri57\li57\sl240\slmult1\qc\cf1\b\f0\rtlch\fs32\&apos;df\&apos;ed\&apos;dd\&apos;ed\&apos;c9 \&apos;c7\&apos;e1\&apos;ca\&apos;cd\&apos;de\&apos;de \&apos;e3\&apos;e4 \&apos;e4\&apos;cc\&apos;c7\&apos;cd \&apos;c7\&apos;e1\&apos;da\&apos;e3\&apos;e1\&apos;ed\&apos;c9\par
        ///
        ///\pard\rtlpar\ri57\li57\sl240\slmult1\qr\cf2\b0\fs28\par
        ///\&apos;de\&apos;e3\&apos;e4\&apos;c7 \&apos;c8\&apos;c5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nastahaqoq {
            get {
                return ResourceManager.GetString("nastahaqoq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #local host Energized Protection # twbh
        ///127.0.0.1 localhost # twbh
        ///127.0.0.1 localhost.localdomain # twbh
        ///127.0.0.1 local # twbh
        ///255.255.255.255 broadcasthost # twbh
        ///::1 localhost # twbh
        ///::1 ip6-localhost # twbh
        ///::1 ip6-loopback # twbh
        ///fe80::1%lo0 localhost # twbh
        ///ff00::0 ip6-localnet # twbh
        ///ff00::0 ip6-mcastprefix # twbh
        ///ff02::1 ip6-allnodes # twbh
        ///ff02::2 ip6-allrouters # twbh
        ///ff02::3 ip6-allhosts # twbh
        ///0.0.0.0 0.0.0.0 # twbh
        ///#tahaqoq # twbh
        ///0.0.0.0 lilhajb.blogspot.com www.lilhajb.blogsp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string qaimatalmawaqi {
            get {
                return ResourceManager.GetString("qaimatalmawaqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap soalwajawab {
            get {
                object obj = ResourceManager.GetObject("soalwajawab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tahaqoq {
            get {
                object obj = ResourceManager.GetObject("tahaqoq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tahaqoqnajah {
            get {
                object obj = ResourceManager.GetObject("tahaqoqnajah", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tahdith {
            get {
                object obj = ResourceManager.GetObject("tahdith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tahmil {
            get {
                object obj = ResourceManager.GetObject("tahmil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tahmillight {
            get {
                object obj = ResourceManager.GetObject("tahmillight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tamma2 {
            get {
                object obj = ResourceManager.GetObject("tamma2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap taqdum {
            get {
                object obj = ResourceManager.GetObject("taqdum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wajiha {
            get {
                object obj = ResourceManager.GetObject("wajiha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
